spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test # MongoDB의 URI
      database: test # 사용할 데이터베이스 이름
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles.active: local
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/emosaac?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
#    username: ssafy
#    password: ssafy
#    hikari:
#      pool-name: jpa-hikari-pool
#      maximum-pool-size: 5
#      jdbc-url: ${spring.datasource.url}
#      username: ${spring.datasource.username}
#      password: ${spring.datasource.password}
#      driver-class-name: ${spring.datasource.driver-class-name}
#      data-source-properties:
#        rewriteBatchedStatements: true

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 50MB #50MB
      max-request-size: 50MB
      enabled: true


server:
  port: 8081